import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, fileUrl, formatPrice, getApiErrorMessage, listingTypeLabel, type ServiceListing } from '../api/Api';
import { Modal } from '../components/Modal';

const statusMeta: Record<ServiceListing['status'], { label: string; className: string }> = {
  active: { label: 'Опубликовано', className: 'bg-[#dff8ee] text-[#157354]' }, hidden: { label: 'Скрыто', className: 'bg-[#f1eef3] text-[#746d80]' },
  moderation: { label: 'На проверке', className: 'bg-[#fff3dc] text-[#9a5b00]' }, closed: { label: 'Закрыто', className: 'bg-[#e7f0ff] text-[#245ca8]' },
};
type Filter = 'all' | ServiceListing['status'];

export const MyAds = () => {
  const navigate = useNavigate(); const [ads, setAds] = useState<ServiceListing[]>([]); const [filter, setFilter] = useState<Filter>('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [deleting, setDeleting] = useState<ServiceListing | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { api.getMyServiceListings().then(setAds).catch(err => setError(getApiErrorMessage(err, 'Не удалось загрузить объявления'))).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => filter === 'all' ? ads : ads.filter(item => item.status === filter), [ads, filter]);
  const remove = async () => { if (!deleting) return; setBusy(true); setError(''); try { await api.deleteServiceListing(deleting.id); setAds(items => items.filter(item => item.id !== deleting.id)); setDeleting(null); } catch (err) { setError(getApiErrorMessage(err, 'Не удалось удалить объявление')); setDeleting(null); } finally { setBusy(false); } };
  const filters: { value: Filter; label: string }[] = [{ value: 'all', label: 'Все' }, { value: 'active', label: 'Опубликованы' }, { value: 'hidden', label: 'Скрыты' }, { value: 'closed', label: 'Закрыты' }, { value: 'moderation', label: 'На проверке' }];

  return <div className="page-shell"><header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Ваши публикации</p><h1 className="page-title mt-2">Мои объявления</h1><p className="page-subtitle mt-3">Управляйте видимостью, обновляйте детали и следите за актуальностью предложений.</p></div><Link to="/adadder" className="button-primary">＋ Новое объявление</Link></header>
      <section className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="surface p-4"><b className="text-2xl font-black">{ads.length}</b><p className="mt-1 text-xs text-[var(--muted)]">всего</p></div><div className="surface p-4"><b className="text-2xl font-black text-[#157354]">{ads.filter(a => a.status === 'active').length}</b><p className="mt-1 text-xs text-[var(--muted)]">в поиске</p></div><div className="surface p-4"><b className="text-2xl font-black text-[var(--brand)]">{ads.filter(a => a.listing_type === 'request').length}</b><p className="mt-1 text-xs text-[var(--muted)]">задач</p></div><Link to="/responses" className="surface group p-4"><b className="text-sm font-black text-[var(--brand)]">Отклики →</b><p className="mt-2 text-xs text-[var(--muted)] group-hover:text-[var(--ink)]">Перейти к сделкам</p></Link></section>
    <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{filters.map(item => <button key={item.value} onClick={() => setFilter(item.value)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${filter === item.value ? 'bg-[var(--ink)] text-white' : 'bg-white text-[var(--muted)] ring-1 ring-[var(--line)]'}`}>{item.label} <span className="opacity-60">{item.value === 'all' ? ads.length : ads.filter(ad => ad.status === item.value).length}</span></button>)}</div>
    {error && <p className="form-error mb-5">{error}</p>}
    {loading ? <div className="empty-state">Загружаем объявления…</div> : visible.length ? <div className="grid gap-4">{visible.map(ad => { const status = statusMeta[ad.status]; const destination = ad.status === 'active' ? `/services/${ad.id}` : `/services/${ad.id}/edit`; return <article key={ad.id} className="surface overflow-hidden p-3 sm:p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><Link to={destination} className="h-40 w-full flex-none overflow-hidden rounded-2xl bg-[#f1edf4] sm:h-28 sm:w-36">{(ad.image_url || ad.images[0]?.url) ? <img src={fileUrl(ad.images[0]?.url || ad.image_url)} alt={ad.title} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-2xl">✦</div>}</Link><div className="min-w-0 flex-1 px-1"><div className="flex flex-wrap gap-2"><span className={`status-pill ${status.className}`}>{status.label}</span><span className="status-pill bg-[#f8f5fa] text-[var(--muted)]">{listingTypeLabel(ad.listing_type)}</span></div><Link to={destination} className="mt-2 block truncate text-lg font-black hover:text-[var(--brand)]">{ad.title}</Link><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm"><b>{formatPrice(ad)}</b><span className="text-[var(--muted)]">{ad.location || 'Место не указано'}</span><span className="text-[var(--muted)]">Обновлено {new Date(ad.updated_at).toLocaleDateString('ru-RU')}</span></div></div><div className="flex gap-2 sm:flex-col"><button onClick={() => navigate(`/services/${ad.id}/edit`)} className="button-secondary flex-1">Изменить</button><button onClick={() => setDeleting(ad)} className="button-quiet flex-1 text-[var(--danger)]">Удалить</button></div></div></article>; })}</div> : <div className="empty-state"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-[var(--brand-soft)] text-2xl">✦</div><h2 className="text-lg font-black text-[var(--ink)]">Здесь пока пусто</h2><p className="mt-2 text-sm">Создайте объявление или выберите другой фильтр.</p></div>}
    <Modal open={!!deleting} onClose={() => !busy && setDeleting(null)} title="Удалить объявление?" description="Оно исчезнет из поиска вместе с историей откликов. Если хотите вернуться позже, лучше скрыть его в настройках."><div className="rounded-2xl bg-[#f8f5fa] p-4 text-sm font-bold">{deleting?.title}</div><div className="modal-actions"><button onClick={() => setDeleting(null)} className="button-secondary">Оставить</button><button disabled={busy} onClick={remove} className="button-danger">{busy ? 'Удаляем…' : 'Удалить навсегда'}</button></div></Modal>
  </div>;
};
