import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, fileUrl, formatPrice, getApiErrorMessage, type AdBlock, type Review, type UserProfile } from '../api/Api';
import { getToken } from '../api/auth';
import { ReportModal } from '../components/FeedbackModals';

export const Profile = () => {
  const { id } = useParams(); const isOwn = !id; const targetId = id ? Number(id) : null;
  const [profile, setProfile] = useState<UserProfile | null>(null); const [ads, setAds] = useState<AdBlock[]>([]); const [reviews, setReviews] = useState<Review[]>([]);
  const [displayName, setDisplayName] = useState(''); const [bio, setBio] = useState(''); const [location, setLocation] = useState(''); const [telegram, setTelegram] = useState(''); const [avatar, setAvatar] = useState<File | null>(null);
  const [editing, setEditing] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [report, setReport] = useState<{ type: 'user' | 'review'; id: number } | null>(null);

  const load = async () => { if (!isOwn && (!targetId || Number.isNaN(targetId))) { setError('Некорректный профиль'); setLoading(false); return; } setLoading(true); setError(''); try { const data = isOwn ? await api.getMe() : await api.getUserProfile(targetId!); setProfile(data); setDisplayName(data.display_name || ''); setBio(data.bio || ''); setLocation(data.location || ''); setTelegram(data.telegram_username || ''); const [userAds, userReviews] = await Promise.all([api.getUserServices(data.id), api.getUserReviews(data.id)]); setAds(userAds); setReviews(userReviews); } catch (err) { setError(getApiErrorMessage(err, 'Не удалось загрузить профиль')); } finally { setLoading(false); } };
  // Reload when navigating between public profiles; form state is populated by load.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [id]);
  const save = async () => { setSaving(true); setError(''); try { let updated = await api.updateMe({ display_name: displayName.trim(), bio: bio.trim(), location: location.trim(), telegram_username: telegram.replace(/^@/, '') }); if (avatar) updated = await api.uploadAvatar(avatar); setProfile(updated); setEditing(false); setAvatar(null); setNotice('Профиль обновлён'); } catch (err) { setError(getApiErrorMessage(err, 'Не удалось сохранить профиль')); } finally { setSaving(false); } };

  if (loading) return <div className="page-shell"><div className="empty-state">Собираем профиль…</div></div>;
  if (!profile) return <div className="page-shell"><div className="empty-state text-red-600">{error || 'Профиль не найден'}</div></div>;
  const name = profile.display_name || profile.username; const initials = name.slice(0, 2).toUpperCase();

  return <div className="page-shell">
    {error && <p className="form-error mb-5">{error}</p>}{notice && <p className="mb-5 rounded-2xl bg-[var(--mint)] p-3 text-sm font-bold text-[#157354]">✓ {notice}</p>}
    <section className="surface relative overflow-hidden p-5 sm:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[var(--brand-soft)] blur-2xl" />
      <div className="relative flex flex-col gap-6 sm:flex-row sm:items-start">
        <div className="grid h-28 w-28 flex-none place-items-center overflow-hidden rounded-[30px] bg-[var(--accent)] text-3xl font-black text-white shadow-xl shadow-blue-200/60">{profile.avatar_url ? <img src={fileUrl(profile.avatar_url)} alt={name} className="h-full w-full object-cover" /> : initials}</div>
        <div className="min-w-0 flex-1"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">{isOwn ? 'Ваш публичный профиль' : 'Профиль специалиста'}</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[var(--ink)] sm:text-4xl">{name}</h1><p className="mt-1 text-sm text-[var(--muted)]">@{profile.username}{profile.location ? ` · ${profile.location}` : ''}</p></div><div className="flex gap-2">{isOwn ? <button onClick={() => setEditing(true)} className="button-primary">Редактировать</button> : getToken() && <button onClick={() => setReport({ type: 'user', id: profile.id })} className="button-secondary">Сообщить о проблеме</button>}</div></div>
          <p className="mt-5 max-w-2xl whitespace-pre-wrap text-sm leading-7 text-[#51495c]">{profile.bio || (isOwn ? 'Добавьте пару строк о себе — живой профиль вызывает больше доверия.' : 'Пользователь пока ничего о себе не рассказал.')}</p>
          <div className="mt-6 flex flex-wrap gap-3"><div className="rounded-2xl bg-[#f4f6f7] px-4 py-3"><b className="block text-xl text-[var(--ink)]">{profile.performer_rating_avg?.toFixed(1) || '—'}</b><span className="text-xs text-[var(--muted)]">как исполнитель · {profile.performer_reviews_count || 0}</span></div><div className="rounded-2xl bg-[#f4f6f7] px-4 py-3"><b className="block text-xl text-[var(--ink)]">{profile.customer_rating_avg?.toFixed(1) || '—'}</b><span className="text-xs text-[var(--muted)]">как заказчик · {profile.customer_reviews_count || 0}</span></div><div className="rounded-2xl bg-[#f4f6f7] px-4 py-3"><b className="block text-xl text-[var(--ink)]">{ads.length}</b><span className="text-xs text-[var(--muted)]">активных объявлений</span></div></div>
        </div>
      </div>
    </section>

    {editing && isOwn && <section className="surface mt-6 p-5 sm:p-7"><div className="mb-6 flex items-start justify-between"><div><h2 className="text-xl font-black">Настройка профиля</h2><p className="mt-1 text-sm text-[var(--muted)]">Эти данные помогут людям понять, можно ли вам доверять.</p></div><button onClick={() => setEditing(false)} className="icon-button">×</button></div><div className="grid gap-5 sm:grid-cols-2"><label className="field"><span>Как к вам обращаться</span><input value={displayName} onChange={e => setDisplayName(e.target.value)} maxLength={100} /></label><label className="field"><span>Город или район</span><input value={location} onChange={e => setLocation(e.target.value)} maxLength={200} /></label><label className="field"><span>Telegram</span><input value={telegram} onChange={e => setTelegram(e.target.value.replace(/^@/, ''))} placeholder="username" /></label><label className="field"><span>Новый аватар</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e => setAvatar(e.target.files?.[0] || null)} /></label><label className="field sm:col-span-2"><span>О себе</span><textarea value={bio} onChange={e => setBio(e.target.value)} rows={5} maxLength={2000} placeholder="Опыт, специализация, подход к работе" /></label></div><div className="modal-actions"><button onClick={() => setEditing(false)} className="button-secondary">Отмена</button><button disabled={saving} onClick={save} className="button-primary">{saving ? 'Сохраняем…' : 'Сохранить'}</button></div></section>}

    <div className="mt-10 grid gap-10 lg:grid-cols-[1.1fr_.9fr]">
      <section><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Витрина</p><h2 className="mt-1 text-2xl font-black">Объявления</h2></div>{isOwn && <Link to="/my-ads" className="text-sm font-bold text-[var(--brand)]">Управлять →</Link>}</div>{ads.length ? <div className="grid gap-4 sm:grid-cols-2">{ads.map(item => <Link key={item.id} to={`/services/${item.id}`} className="surface group overflow-hidden transition hover:-translate-y-1"><div className="aspect-[16/10] overflow-hidden bg-[#f1edf4]">{(item.image_url || item.images[0]?.url) ? <img src={fileUrl(item.images[0]?.url || item.image_url)} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid h-full place-items-center text-3xl">✦</div>}</div><div className="p-4"><h3 className="line-clamp-2 font-black">{item.title}</h3><p className="mt-2 font-black text-[var(--brand)]">{formatPrice(item)}</p></div></Link>)}</div> : <div className="empty-state">Активных объявлений пока нет.</div>}</section>
      <section><div className="mb-5"><p className="eyebrow">Репутация</p><h2 className="mt-1 text-2xl font-black">Отзывы</h2></div>{reviews.length ? <div className="space-y-4">{reviews.map(item => <article key={item.id} className="surface p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-black">{item.author.display_name || item.author.username}</p><p className="text-xs text-[var(--muted)]">Подтверждённая сделка · {item.review_type === 'performer' ? 'об исполнителе' : 'о заказчике'}</p></div><span className="status-pill bg-[#fff3dc] text-[#9a5b00]">★ {item.rating}.0</span></div>{item.text && <p className="mt-4 text-sm leading-6 text-[#445064]">{item.text}</p>}{getToken() && item.author.id !== profile.id && <button onClick={() => setReport({ type: 'review', id: item.id })} className="mt-3 text-xs font-bold text-[var(--muted)] hover:text-[var(--danger)]">Пожаловаться</button>}</article>)}</div> : <div className="empty-state">После завершённых сделок здесь появятся отзывы.</div>}</section>
    </div>
    {report && <ReportModal open targetType={report.type} targetId={report.id} onClose={() => setReport(null)} onSuccess={() => setNotice('Жалоба отправлена модератору')} />}
  </div>;
};
